### ISSUE TITLE
When "to" not specified, program throws exception error.

### ISSUE THREAD

**Issue by mattcbrowne** [nightbat13131/Sails_and_Sabers_Helper#1]
Recommend setting defaults

Traceback (most recent call last):
  File "pandas\core\computation\scope.py", line 244, in resolve
KeyError: 'To'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Bloodline Heros of Lithas - Sails and Sabers Helper.py", line 207, in <module>
  File "window_manipulator.py", line 198, in process_event_input
  File "window_manipulator.py", line 292, in populate_long_path_tab
  File "island_trader_classes.py", line 493, in best_long_path
  File "island_trader_classes.py", line 469, in __calculations_for_best_long_path
  File "pandas\core\frame.py", line 4440, in query
  File "pandas\core\frame.py", line 4566, in eval
  File "pandas\core\computation\eval.py", line 336, in eval
  File "pandas\core\computation\expr.py", line 809, in __init__
  File "pandas\core\computation\expr.py", line 828, in parse
  File "pandas\core\computation\expr.py", line 415, in visit
  File "pandas\core\computation\expr.py", line 421, in visit_Module
  File "pandas\core\computation\expr.py", line 415, in visit
  File "pandas\core\computation\expr.py", line 424, in visit_Expr
  File "pandas\core\computation\expr.py", line 415, in visit
  File "pandas\core\computation\expr.py", line 746, in visit_BoolOp
  File "pandas\core\computation\expr.py", line 740, in visitor
  File "pandas\core\computation\expr.py", line 735, in _try_visit_binop
  File "pandas\core\computation\expr.py", line 415, in visit
  File "pandas\core\computation\expr.py", line 719, in visit_Compare
  File "pandas\core\computation\expr.py", line 415, in visit
  File "pandas\core\computation\expr.py", line 535, in visit_BinOp
  File "pandas\core\computation\expr.py", line 455, in _maybe_transform_eq_ne
  File "pandas\core\computation\expr.py", line 415, in visit
  File "pandas\core\computation\expr.py", line 548, in visit_Name
  File "pandas\core\computation\ops.py", line 86, in __init__
  File "pandas\core\computation\ops.py", line 110, in _resolve_name
  File "pandas\core\computation\scope.py", line 246, in resolve
pandas.errors.UndefinedVariableError: name 'To' is not defined

**Comment by nightbat13131** [comment]
Thanks for the bug. Error found and implementing fix today.

**Comment by nightbat13131** [comment]
An invalid header name was being used. Whitespace was being trimmed by some parts of Pandas and not others, causing a mismatch between headers and query. Other minor bugs also found and fixed related to protecting against unexpected clicks an inputes.
